### ISSUE TITLE
Przesuwanie mapy na dużym powiększeniu

### ISSUE THREAD

**Issue by seazaki** [jzmudzinski/adamant-octo-barnacle#1]

**Comment by jzmudzinski** [comment]
@seazaki Ale na czym polega problem?

**Comment by seazaki** [comment]
Mapą można przesuwać tylko do pewnego stopnia zbliżenia. Jak maksymalnie przybliżę, już nie mogę- muszę oddalić, żeby przesunąć i znowu przybliżyć.

**Comment by jzmudzinski** [comment]
Możesz nagrać filmik z ekranu? Bo nie do końca kumam.
